--- 
- name: install and configure httpd
  hosts: all
  become: true
  tasks:
  - name: Installing httpd
    ansible.builtin.yum:
     name: httpd
     state: latest
  - name: Installing httpd
    ansible.builtin.yum:
     name: docker
     state: latest
  - name: Start service httpd, if not started
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes
